DELETE FROM users;
delete from sqlite_sequence where name="users";
VACUUM;

INSERT INTO "main"."users" VALUES (1, 'Anonymous', 'Jubay, San Antonio, Liloan, Cebu', '09173242410 / 4241684', 1, '', '2015-04-27T00:48:08.299Z', 'images/profile/avatar9.jpg', 'Jubay, Liloan', 0.0);

DELETE FROM orders;
DELETE FROM payments;
DELETE FROM items;
DELETE FROM fees;
DELETE FROM campaign_users;
DELETE FROM campaigns;
DELETE FROM expenses;
DELETE FROM logs;
DELETE FROM warranties;
DELETE FROM reminders;
delete from sqlite_sequence where name="orders";
delete from sqlite_sequence where name="payments";
delete from sqlite_sequence where name="items";
delete from sqlite_sequence where name="fees";
delete from sqlite_sequence where name="campaign_users";
delete from sqlite_sequence where name="campaigns";
delete from sqlite_sequence where name="expenses";
delete from sqlite_sequence where name="logs";
delete from sqlite_sequence where name="warranties";
delete from sqlite_sequence where name="reminders";
VACUUM;

INSERT INTO "main"."logs" VALUES (1, 'Welcome Message', 'Unread', 'This is your first Log.
If you have Questions/Suggestions/Bug Report, Feel free to contact me @ my mobile number 09173242410

Enjoy Using Barista Choi POS', '""', '2015-05-11T12:12:44.713Z');

DELETE FROM groups;
delete from sqlite_sequence where name="groups";
VACUUM;

INSERT INTO "main"."groups" VALUES (1, 'Default');
INSERT INTO "main"."groups" VALUES (2, 'Points');

DELETE FROM admins;
delete from sqlite_sequence where name="admins";
VACUUM;

INSERT INTO "main"."admins" VALUES (1, 'Admin', 1234, 'Admin', 'images/profile/avatar11.jpg');
INSERT INTO "main"."admins" VALUES (2, 'Cashier 1', 1234, 'Cashier', 'images/nophoto.jpg');

DELETE FROM product_categories;
delete from sqlite_sequence where name="product_categories";
VACUUM;

INSERT INTO "main"."product_categories" VALUES (1, 'Uncategorized');
INSERT INTO "main"."product_categories" VALUES (2, 'Machines');
INSERT INTO "main"."product_categories" VALUES (3, 'Powders');
INSERT INTO "main"."product_categories" VALUES (4, 'Paper Cups');
INSERT INTO "main"."product_categories" VALUES (5, 'Spare Parts');

DELETE FROM products;
delete from sqlite_sequence where name="products";
VACUUM;

INSERT INTO "main"."products" VALUES (1, 'Others', '', 'images/noimageproduct.jpg', 0, 'unit', 0.0, 0.0, 1, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (2, 'Coffee Vending Machine', '', 'images/products/400x400_machine.png', 0, 'unit', 12000.0, 11000.0, 2, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (3, '6.5oz Paper Cup', '', 'images/products/400x400_resize_1370827545.png.png', 0, 'pc', 0.7, 0.6, 4, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (4, 'Milky Choco Loco', '', 'images/products/choco.jpg', 0, 'kg', 170.0, 155.0, 3, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (5, 'Caramel Macchiato', '', 'images/products/caramel.jpg', 0, 'kg', 170.0, 155.0, 3, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (6, 'Coffee Pinoy Blend', '', 'images/products/pinoy.jpg', 0, 'kg', 170.0, 155.0, 3, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (7, 'Mocha Cappuccino', '', 'images/products/mocha.jpg', 0, 'kg', 170.0, 155.0, 3, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (9, 'Creamy Milk tea', '', 'images/products/milktea.jpg', 0, 'kg', 170.0, 155.0, 3, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (10, 'Coffee White', '', 'images/products/white.jpg', 0, 'kg', 170.0, 155.0, 3, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (11, 'B-Type_Button', '', 'images/noimageproduct.jpg', 0, 'pc', 55.0, 35.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (12, 'B-Type Button Ornament', '', 'images/noimageproduct.jpg', 0, 'pc', 55.0, 35.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (13, 'B-Type Display Lens', '', 'images/noimageproduct.jpg', 0, 'pc', 40.0, 25.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (14, 'Lightboard', '', 'images/noimageproduct.jpg', 0, 'pc', 25.0, 15.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (15, 'B#Operation Panel', '', 'images/noimageproduct.jpg', 0, 'pc', 115.0, 75.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (16, 'B-Type Down Decorative Panel', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (17, 'B-Type Tabletting', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (19, 'B-Type Front Case', '', 'images/noimageproduct.jpg', 0, 'pc', 2145.0, 1430.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (26, 'Key', '', 'images/noimageproduct.jpg', 0, 'pc', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (27, 'C-Type Lock', '', 'images/noimageproduct.jpg', 0, 'pc', 115.0, 75.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (28, 'Right Decoration Panel', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (29, 'Big Button', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (30, 'Coin Slot', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (31, 'Coin Sensor', '', 'images/noimageproduct.jpg', 0, 'pc', 120.0, 80.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (32, 'Coin Insert Frame', '', 'images/noimageproduct.jpg', 0, 'pc', 255.0, 170.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (33, 'Micro Switch Holder', '', 'images/noimageproduct.jpg', 0, 'pc', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (34, 'Coin Box Frame', '', 'images/noimageproduct.jpg', 0, 'pc', 12.0, 8.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (35, 'Cover Of Falling Cup Device', '', 'images/noimageproduct.jpg', 0, 'pc', 75.0, 50.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (36, 'Base Of Falling Cup Device', '', 'images/noimageproduct.jpg', 0, 'pc', 105.0, 70.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (37, 'Switch 1', '', 'images/noimageproduct.jpg', 0, 'pc', 75.0, 50.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (38, 'Switch 2', '', 'images/noimageproduct.jpg', 0, 'pc', 105.0, 70.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (39, 'Cam', '', 'images/noimageproduct.jpg', 0, 'pc', 2.0, 1.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (40, 'Internal Gear', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (41, 'Connecting Rod Of Falling Cup Device', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (42, 'Press Cup Gear', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (43, 'Falling Cup Motor', '', 'images/noimageproduct.jpg', 0, 'pc', 195.0, 130.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (44, 'Outlet Of Falling Cup', '', 'images/noimageproduct.jpg', 0, 'pc', 40.0, 25.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (45, 'Hot Water Dispense', '', 'images/noimageproduct.jpg', 0, 'pc', 1350.0, 900.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (46, 'Water Temperature Sensor', '', 'images/noimageproduct.jpg', 0, 'pc', 120.0, 80.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (47, 'Seal Of Water Temperature', '', 'images/noimageproduct.jpg', 0, 'pc', 10.0, 5.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (48, 'Electromagnetism Valve Steel Loop Line', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (49, 'Wire Of Heating Tube', '', 'images/noimageproduct.jpg', 0, 'pc', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (50, 'Prevent Dry Temperature Sensor', '', 'images/noimageproduct.jpg', 0, 'pc', 90.0, 60.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (51, 'Discharging Tube', '', 'images/noimageproduct.jpg', 0, 'pc', 150.0, 100.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (52, 'Big S Tube', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (53, 'Thermal Insulation Foam', '', 'images/noimageproduct.jpg', 0, 'pc', 40.0, 25.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (54, 'Rubber Foot', '', 'images/noimageproduct.jpg', 0, 'pc', 6.0, 4.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (55, 'O Circle Of Outlet Valve', '', 'images/noimageproduct.jpg', 0, 'pc', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (56, 'Export Water Electromagnetsm Control', '', 'images/noimageproduct.jpg', 0, 'pc', 600.0, 400.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (57, 'Water Entry Pedestal', '', 'images/noimageproduct.jpg', 0, 'pc', 25.0, 15.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (58, 'Water Tank Base', '', 'images/noimageproduct.jpg', 0, 'pc', 75.0, 50.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (59, 'Coin Container', '', 'images/noimageproduct.jpg', 0, 'pc', 60.0, 40.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (60, 'Cup Cylinder', '', 'images/noimageproduct.jpg', 0, 'pc', 90.0, 60.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (61, 'Power Switch', '', 'images/noimageproduct.jpg', 0, 'pc', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (62, 'Line Heating Switch', '', 'images/noimageproduct.jpg', 0, 'pc', 40.0, 25.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (63, 'Enactment Switch', '', 'images/noimageproduct.jpg', 0, 'pc', 60.0, 40.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (64, 'Button Switch', '', 'images/noimageproduct.jpg', 0, 'pc', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (65, 'Water Entry Joint', '', 'images/noimageproduct.jpg', 0, 'pc', 6.0, 4.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (66, 'Bucket Seal', '', 'images/noimageproduct.jpg', 0, 'pc', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (67, 'Beverage Outlet Holder', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (68, 'Mixing Vent', '', 'images/noimageproduct.jpg', 0, 'pc', 10.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (69, 'B#Funnel', '', 'images/noimageproduct.jpg', 0, 'pc', 15.0, 10.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (70, 'B#Funnel Cover', '', 'images/noimageproduct.jpg', 0, 'pc', 15.0, 10.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (71, 'B#Mixing Bucket', '', 'images/noimageproduct.jpg', 0, 'pc', 25.0, 15.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (72, 'Small S Pipe', '', 'images/noimageproduct.jpg', 0, 'pc', 20.0, 12.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (73, 'Drink Outlet', '', 'images/noimageproduct.jpg', 0, 'pc', 15.0, 8.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (74, 'Insect Prevention Cover', '', 'images/noimageproduct.jpg', 0, 'pc', 75.0, 50.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (75, 'Water Receptacle', '', 'images/noimageproduct.jpg', 0, 'pc', 105.0, 70.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (76, 'B#Water Receptacle Veneer', '', 'images/noimageproduct.jpg', 0, 'pc', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (77, 'B#Vane', '', 'images/noimageproduct.jpg', 0, 'pc', 6.0, 4.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (78, 'Vent Pipe', '', 'images/noimageproduct.jpg', 0, 'pc', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (79, 'Vent Water Stopper', '', 'images/noimageproduct.jpg', 0, 'pc', 10.0, 5.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (80, 'Inner Water Tank', '', 'images/noimageproduct.jpg', 0, 'pc', 105.0, 70.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (81, 'Seal Ring Of Water Tank', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (82, 'Water Level Sensor', '', 'images/noimageproduct.jpg', 0, 'pc', 135.0, 90.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (83, 'Export Gear Wheel', '', 'images/noimageproduct.jpg', 0, 'pc', 5.0, 3.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (84, 'Control PC', '', 'images/noimageproduct.jpg', 0, 'pc', 2700.0, 1800.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (85, 'Protective Film', '', 'images/noimageproduct.jpg', 0, 'pc', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (86, 'Transformer', '', 'images/noimageproduct.jpg', 0, 'pc', 1050.0, 700.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (87, 'Mixing Gear CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (88, 'Mixing Steel Wire CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 10.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (89, 'Feeding Axle CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (90, 'O Cirle Of Feeding Axle CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (91, 'Small Canister CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 165.0, 110.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (92, 'Jump Ring CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 10.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (93, 'Raw Material Outlet CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 15.0, 10.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (94, 'Canister Lid CNSTR', '', 'images/noimageproduct.jpg', 0, 'pc', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (95, 'Fuse', '', 'images/noimageproduct.jpg', 0, 'pc', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (96, 'Fuse Seating', '', 'images/noimageproduct.jpg', 0, 'pc', 60.0, 40.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (97, 'Center Tube', '', 'images/noimageproduct.jpg', 0, 'pc', 12.0, 8.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (98, 'Display', '', 'images/noimageproduct.jpg', 0, 'pc', 615.0, 410.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (100, 'Fan Housing', '', 'images/noimageproduct.jpg', 0, 'pc', 25.0, 15.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (101, 'Fan', '', 'images/noimageproduct.jpg', 0, 'pc', 150.0, 100.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (120, 'B# Wire of Motor Control', '', 'images/noimageproduct.jpg', 0, 'unit', 255.0, 170.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (121, 'B# wire of controlling board', '', 'images/noimageproduct.jpg', 0, 'unit', 225.0, 150.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (122, 'wire of line heating', '', 'images/noimageproduct.jpg', 0, 'unit', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (123, 'B# wire of setting parameter', '', 'images/noimageproduct.jpg', 0, 'unit', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (124, 'B# Exchange Wire', '', 'images/noimageproduct.jpg', 0, 'unit', 180.0, 120.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (125, 'Exhaust Fan Wire', '', 'images/noimageproduct.jpg', 0, 'unit', 30.0, 20.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (126, 'Line Heater', '', 'images/noimageproduct.jpg', 0, 'unit', 135.0, 90.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (127, 'raw material bucket seal', '', 'images/noimageproduct.jpg', 0, 'unit', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (128, 'Raw Material Bucket Seal Cushion', '', 'images/noimageproduct.jpg', 0, 'unit', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (129, 'Big Cable Clip', '', 'images/noimageproduct.jpg', 0, 'unit', 8.0, 5.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (130, 'Small Cable Clip', '', 'images/noimageproduct.jpg', 0, 'unit', 8.0, 5.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (131, 'Vent Syphon', '', 'images/noimageproduct.jpg', 0, 'unit', 20.0, 13.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (132, 'Oin Container', '', 'images/noimageproduct.jpg', 0, 'unit', 6.0, 4.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (133, 'Valve Plug', '', 'images/noimageproduct.jpg', 0, 'unit', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (134, 'One-way Valve', '', 'images/noimageproduct.jpg', 0, 'unit', 21.0, 14.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (135, 'Beater', '', 'images/noimageproduct.jpg', 0, 'unit', 450.0, 300.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (136, 'Sealing Gasket', '', 'images/noimageproduct.jpg', 0, 'unit', 3.0, 2.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (137, 'B# Mixing Motor Base', '', 'images/noimageproduct.jpg', 0, 'unit', 53.0, 35.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (138, 'Generator System of Inputting Material', '', 'images/noimageproduct.jpg', 0, 'unit', 795.0, 530.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (139, 'Interval Column', '', 'images/noimageproduct.jpg', 0, 'unit', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (140, 'Hinger on Top of Door', '', 'images/noimageproduct.jpg', 0, 'unit', 53.0, 35.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (141, 'Hinger Down Door', '', 'images/noimageproduct.jpg', 0, 'unit', 53.0, 35.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (142, 'Knocker Cover', '', 'images/noimageproduct.jpg', 0, 'unit', 15.0, 10.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (143, 'Door Layer Board', '', 'images/noimageproduct.jpg', 0, 'unit', 9.0, 6.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (144, 'B# Door Pressure Plate', '', 'images/noimageproduct.jpg', 0, 'unit', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (145, 'Joint Rack of Water Entry', '', 'images/noimageproduct.jpg', 0, 'unit', 12.0, 8.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (146, 'Support of Down Separator Board', '', 'images/noimageproduct.jpg', 0, 'unit', 45.0, 30.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (147, 'Power Line', '', 'images/noimageproduct.jpg', 0, 'unit', 180.0, 120.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (148, 'Line Clasp', '', 'images/noimageproduct.jpg', 0, 'unit', 6.0, 3.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (149, 'Upper Clapboard', '', 'images/noimageproduct.jpg', 0, 'unit', 450.0, 300.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (150, 'Down Clapboard', '', 'images/noimageproduct.jpg', 0, 'unit', 450.0, 300.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (151, 'Down Panel on Back', '', 'images/noimageproduct.jpg', 0, 'unit', 225.0, 150.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (152, 'Upper Panel on Back', '', 'images/noimageproduct.jpg', 0, 'unit', 180.0, 120.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (153, 'Baseboard', '', 'images/noimageproduct.jpg', 0, 'unit', 450.0, 300.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (154, 'B# Shell', '', 'images/noimageproduct.jpg', 0, 'unit', 2100.0, 1400.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (155, 'Upper Clap Board', '', 'images/noimageproduct.jpg', 0, 'unit', 450.0, 300.0, 5, 0, 0.0, 0);
INSERT INTO "main"."products" VALUES (156, 'Down Clapboard', '', 'images/noimageproduct.jpg', 0, 'unit', 450.0, 300.0, 5, 0, 0.0, 0);


DELETE FROM settings;
delete from sqlite_sequence where name="settings";
VACUUM;

INSERT INTO "main"."settings" VALUES (1, 'Branch Name', 'Cebu - Liloan');
INSERT INTO "main"."settings" VALUES (2, 'Branch Address', 'Jubay, San Antonio, Liloan Cebu');
INSERT INTO "main"."settings" VALUES (3, 'Branch Contact', '(032) 424-1684');
INSERT INTO "main"."settings" VALUES (4, 'Printing Footer', 'Barista Choi Vending Solutions Inc.');
INSERT INTO "main"."settings" VALUES (5, 'Printing Sub', 'Open from Monday to Friday 8am to 5pm');
INSERT INTO "main"."settings" VALUES (6, 'Report Powders', 3);
INSERT INTO "main"."settings" VALUES (7, 'Report Machines', 2);
INSERT INTO "main"."settings" VALUES (8, 'Report Cups', 4);
INSERT INTO "main"."settings" VALUES (9, 'Report Parts', 5);
INSERT INTO "main"."settings" VALUES (10, 'Warranty Maintenance', 30);
INSERT INTO "main"."settings" VALUES (11, 'Warranty Void', 30);
INSERT INTO "main"."settings" VALUES (12, 'Points Group', 2);

